title: Cody's Personal Blog
description: This site contains the personal blog of Cody Merritt Anhorn.
paginate: 5
paginate_path: "/blog/page:num/"
plugins:
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
author:
    name: Cody Merritt Anhorn
    uri: https://codyanhorn.tech/
    email: cody.anhorn+blog@hotmail.com
    twitter: CodyAnhorn
defaults:
    - scope:
        path: ""
      values:
        image: /image/EventHorizonLogo.png